### ISSUE TITLE
Use a more universal money indication

### ISSUE THREAD

**Issue by alanpearce** [Brunty/checker-services#21]
Only ~70M people use the £ symbol for their local currency. How about a nice inclusive 💳 or just simply "price" or "cost"?

**Comment by Brunty** [comment]
Good call - I like the use of emojis everywhere else, so will add it for the price sections of the existing readme (unless you want to and get that sweet-sweet contributor kudos) ;)

**Comment by alanpearce** [comment]
I'll do it! :)
